config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :teams, only: [:create, :show] do
    resources :projects, only: [:index, :create, :new]
    resources :events, only: :index
  end
  resources :projects, only: [:show] do
    resources :todos, only: [:create, :show, :destroy]
  end
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  post "todos/change_complete_todo" => "todos#change_complete"
  resources :todos do
    member do
      get :appoint_user, :edit_user, :edit_date, :comment
    end
  end
  resources :sessions, only: [:new, :create]
end

app/models/project.rb
class Project < ApplicationRecord
  include Eventable
  has_many :todos, dependent: :destroy
  has_many :accesses, dependent: :destroy
  has_many :users, through: :accesses

  def is_access?(user_id)
    self.accesses.where(user_id: user_id).empty? ? false :true
  end
end

app/controllers/projects_controller.rb
# encoding=utf-8
class ProjectsController < ApplicationController
  before_action :signed_in_user
  before_action :access_user, only: :show

  def index
    @team = Team.find(params[:team_id])
    @projects = @team.projects    
  end

  def new
    @team = Team.find(params[:team_id])
    @project = @team.projects.build
    @members = @team.users
  end

  def create
    user_ids = params[:user_ids]
    @team = Team.find(params[:team_id])
    project = @team.projects.build(project_params)
    if project.save
      user_ids.each do |user_id|
        Access.create(user_id: user_id, project_id: project.id)
      end
      redirect_to project_path(project)
    else
      redirect_to root_path
    end
  end

  def show
    @todos = @project.todos
    @unfinish_count = @todos.unfinish.count
    @project_users = @project.users
    @todos = @todos.order(id: :desc).paginate(:page => params[:page])
  end

  private
    def project_params
      params.require(:project).permit(:name)
    end

    def access_user
      @project = Project.find(params[:id])
      unless @project.is_access?(current_user.id)
        flash[:success] = "没有权限访问该项目"
        redirect_to root_path 
      end
    end

end

app/views/projects/index.html.erb
<h1>所有项目</h1>
<h3><%= link_to "新建项目", new_team_project_path(@team) %></h3>
<h3><%= link_to "动态", team_events_path(@team) %></h3>
<ul>
  <% if @projects.any? %>
      <% @projects.each do |project| %>
        <li><%= link_to project.name, project_path(project) %></li>
      <% end %>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h1>创建项目</h1>
<%= form_for [@team, @project] do |f| %>
  <%= f.label :name, "项目名称" %>
  <%= f.text_field :name %> <br/>
  <% @members.each do |m| %>
    <label>
      <%= check_box_tag 'user_ids[]', m.id, false %>
      <%= m.nickname %>
    </label>
  <% end %>
  <br/>
  <%= f.submit "创建项目" %>
<% end %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<span>待处理任务: <%= @unfinish_count %></span>
<span>成员: <%= @project_users.count %></span>
<h1>创建任务</h1>
<%= form_for [@project, @project.todos.build] do |f| %>
  <%= f.label :name, "新的任务" %>
  <%= f.text_field :name %>
  <%= f.label :end_time_at, "任务截至时间" %>
  <%= f.text_field :end_time_at, class: "date-picker" %>
  <%= f.label :user_id, "将任务指派给" %>
  <%= f.select 'user_id', options_for_select(@project_users.map { |pu| [pu.nickname, pu.id] }), include_blank: true %>
  <%= f.submit "创建任务" %>
<% end %>
<h2>任务列表</h2>
<ul id ="todos">
  <% @todos.each do |todo| %>
    <%= render 'todos/todo', todo: todo %>
  <% end %>
</ul>

<%= will_paginate @todos, class: "endless_paginate" %>

<script type="text/javascript">
  // 日历
  $('.date-picker').on("click", function(){
    $(this).datetimepicker({ format: 'yyyy-mm-dd',language: 'zh-CN',startView: 2, minView: 2, autoclose: true});
  });

  $(".todo").on("change", function(){
    var todo_id = $(this).data("todo");
    console.log(todo_id);
    $.ajax({
      type: "POST",
      url: "/todos/change_complete_todo",
      data: {todo_id: todo_id},
      success: function(data) { 

      },
      error: function(data){

      }
    })
  });
</script>

app/views/projects/show.js.erb
$('#todos').append('<%= j render(@todos) %>');
<% if @todos.next_page %>
  $('.endless_paginate').replaceWith('<%= j will_paginate(@todos, class: "endless_paginate") %>');
  $(".footer").remove();
<% else %>
  $('.endless_paginate').remove();
<% end %>
<% sleep 0.8 %>